apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: school-hub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/subhrajyotipodder/school-hub.git
    targetRevision: HEAD
    path: helm/school-hub
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: school-hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
